<?php
/**
 * Created by PhpStorm.
 * User: liangxz@szljfkj.com
 * Date: 2017/3/29
 * Time: 14:03
 * 代理商的导航菜单配置
 */
return[
    [
        'id'    => 1,
        'parent_id' => 0,
        'title_cn'  => '账号管理',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1001',
    ],
    [
        'id'    => 2,
        'parent_id' => 1,
        'title_cn'  => '玩家管理',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1002',
    ],
    [
        'id'    => 3,
        'parent_id' => 1,
        'title_cn'  => '代理维护',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1003',
    ],
    [
        'id'    => 4,
        'parent_id' => 0,
        'title_cn'  => '报表系统',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1004',
    ],
    [
        'id'    => 5,
        'parent_id' => 4,
        'title_cn'  => '查询现金流',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1005',
    ],
    [
        'id'    => 6,
        'parent_id' => 0,
        'title_cn'  => '游戏数据统计',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1006',
    ],
    [
        'id'    => 7,
        'parent_id' => 6,
        'title_cn'  => '查询总投注额',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1007',
    ],
    [
        'id'    => 8,
        'parent_id' => 6,
        'title_cn'  => '查询制定玩家',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1008',
    ],
    [
        'id'    => 9,
        'parent_id' => 6,
        'title_cn'  => '查询厅',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1009',
    ],
    [
        'id'    => 10,
        'parent_id' => 6,
        'title_cn'  => '查询游戏',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1010',
    ],
    [
        'id'    => 11,
        'parent_id' => 6,
        'title_cn'  => '查询桌次',
        'title_en'  => '',
        'class'     => 0,
        'link_url'  => '',
        'icon'      => '',
        'state'     => 1,
        'sort_id'   => 1,
        'menu_code' => 'A1011',
    ],

];